version: '3'
services:
  php:
    container_name: wemovie_php
    build:
      context: .
      dockerfile: docker/images/php8/Dockerfile
    volumes:
      - ./:/var/www
    tty: true

  nginx:
    container_name: wemovie_nginx
    build: docker/images/nginx
    ports:
      - 8009:80
    depends_on:
      - php
    links:
      - php
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/var/logs/nginx/:/var/log/nginx